export {default as Home } from "./home/Home"
export {default as Contact } from "./contact/Contact"
export {default as Login } from "./auth/Login"
export {default as SingUp } from "./auth/SingUp"
export {default as Reset } from "./auth/Reset"
export {default as Admin} from "./admin/Admin"
export {default as Cart} from "./cart/Cart"
export {default as OrderHistory} from "./orderHistory/OrderHistory"
export {default as Check} from "./checkout/Check"